version: "3.8"
services:
  smartball-dev:
    build:
      context: ./../../../
      dockerfile: tools/docker/develop/Dockerfile
    restart: always
    ports:
      - 3300:3300
    volumes:
      - ./../../..:/prj
    command: 
      - tail
      - -f
      - /dev/null